service: js13kGames-bot-v2

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - ./**

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: stage
  logRetentionInDays: 14
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket*"
      Resource:
        - "arn:aws:s3:::*"

    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"

  environment:
    AWS_BUCKET_NAME: js13kgames-entry-previeww
    BROWSERSTACK_KEY: ${env:BROWSERSTACK_KEY}
    BROWSERSTACK_USER: ${env:BROWSERSTACK_USER}

resources:
  Resources:
    deployBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        WebsiteConfiguration:
          IndexDocument: "index.html"

        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - "GET"
              AllowedOrigins:
                - "*"
        BucketName: js13kgames-entry-previeww

functions:
  bundleAnalyzer:
    package:
      include:
        - build/bundle-analyzer/index.js
    handler: build/bundle-analyzer/index.handle
    events:
      - http: POST analyze-bundle

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - "*/*"
      - "multipart/form-data"
      - "image/*"
