useDotenv: true

service: js13kGames-bot
configValidationMode: off
provider:
  name: scaleway
  runtime: node18

  scwToken: ${env:SCALEWAY_SECRET_KEY}
  scwProject: ${env:SCALEWAY_PROJECT_ID}
  scwRegion: ${env:SCALEWAY_REGION}

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - "!**/*"
    - "build/**/*"
    - "package.json"

functions:
  analyze:
    description: receive a zip file containing the game. Attempt to run it. Report issues.
    handler: build/handler.handle
    memoryLimit: 512
    timeout: 300s
    secret:
      SCALEWAY_REGION: ${env:SCALEWAY_REGION}
      SCALEWAY_ACCESS_KEY: ${env:SCALEWAY_ACCESS_KEY}
      SCALEWAY_SECRET_KEY: ${env:SCALEWAY_SECRET_KEY}
    env:
      SCALEWAY_S3_ENDPOINT: ${env:SCALEWAY_S3_ENDPOINT}
    custom_domains:
      - ${env:SUBMISSION_CUSTOM_DOMAIN}
